name = "MLJTransforms"
uuid = "23777cdb-d90c-4eb0-a694-7c2b83d5c1d6"
authors = ["Essam <essamwisam@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
